CREATE TABLE SCHEMA1.TEST (
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    NR_DOCUMENTO VARCHAR(14) NOT NULL DEFAULT '',
    DT_INCLUSAO TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    DT_ALTERACAO TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (ID)
);

COMMENT ON COLUMN SCHEMA1.TEST.ID IS 'Identificação do registro';
COMMENT ON COLUMN SCHEMA1.TEST.NR_DOCUMENTO IS 'CPF/CNPJ';
COMMENT ON COLUMN SCHEMA1.TEST.DT_INCLUSAO IS 'Data de geração e inclusão do registro';
COMMENT ON COLUMN SCHEMA1.TEST.DT_ALTERACAO IS 'Data de atualização do registro';
