services:
  db:
    build: .
    privileged: true
    restart: always
    ports:
      - "50001:50000"
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: ${DB2INST1_PASSWORD}
      DBNAME: ${DBNAME}
      DB2COMM: TCPIP
