services:
  db2_pertama:
    container_name: db21
    build: .
    privileged: true
    restart: always
    ports:
      - "127.0.0.1:6001:50000"
    networks:
      - ibm_db2
    environment:
      LICENSE: accept
      DB2INSTANCE: ${DB2NAME}_1
      DB2INST1_PASSWORD: ${INSTANCE1_PASSWORD}
      DBNAME: ${DBNAME}
      DB2COMM: TCPIP
      HADR_ENABLED: true
      ETCD_ENDPOINT: 127.0.0.1:6001,127.0.0.1:6002
    volumes:
      - ./db21/database:/database
      - ./db21/data:/home/${DB2NAME}_1/data

  db2_kedua:
    container_name: db22
    build: .
    privileged: true
    restart: always
    ports:
      - "127.0.0.1:6002:50000"
    networks:
      - ibm_db2
    environment:
      LICENSE: accept
      DB2INSTANCE: ${DB2NAME}_2
      DB2INST1_PASSWORD: ${INSTANCE2_PASSWORD}
      DBNAME: ${DBNAME}
      DB2COMM: TCPIP
      HADR_ENABLED: true
      ETCD_ENDPOINT: 127.0.0.1:6001,127.0.0.1:6002
    volumes:
      - ./db22/database:/database
      - ./db22/data:/home/${DB2NAME}_2/data
networks:
  ibm_db2:
    name: db2net
    driver: bridge
